[package]
name = 'The Dank Duel'
version = '1.0.0'

[addresses]
# Testnet Address
duel = "a7a691856c0f756c1844e2fe033ec425e49511f972887e0e8b2b5f136db5b29d"


[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-framework'

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib"
rev = "mainnet"